#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/bash

# Check for console.log in staged files

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

if git diff --cached --name-only -- '*.ts' '*.tsx' | xargs grep -n 'console\.log'; then
  echo -e "${RED} ❌ unexpected console.log statements  ${NC}"
  exit 1
fi

# If no issues are found, the commit proceeds.
exit 0

npx lint-staged



